/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SemestersRouteImport } from './routes/semesters'
import { Route as PucExplainerRouteImport } from './routes/puc-explainer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SemestersIndexRouteImport } from './routes/semesters.index'
import { Route as SemestersNewRouteImport } from './routes/semesters.new'
import { Route as SemesterSemesterIdRouteImport } from './routes/semester.$semesterId'
import { Route as SemesterSemesterIdIndexRouteImport } from './routes/semester.$semesterId.index'
import { Route as SemesterSemesterIdExportRouteImport } from './routes/semester.$semesterId.export'
import { Route as SemesterSemesterIdEditRouteImport } from './routes/semester.$semesterId.edit'
import { Route as SemesterSemesterIdCalendarRouteImport } from './routes/semester.$semesterId.calendar'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SemesterSemesterIdSubjectsNewRouteImport } from './routes/semester.$semesterId.subjects.new'
import { Route as SemesterSemesterIdSubjectSubjectIdRouteImport } from './routes/semester.$semesterId.subject.$subjectId'
import { Route as SemesterSemesterIdSubjectSubjectIdIndexRouteImport } from './routes/semester.$semesterId.subject.$subjectId.index'
import { Route as SemesterSemesterIdSubjectSubjectIdReviewRouteImport } from './routes/semester.$semesterId.subject.$subjectId.review'
import { Route as SemesterSemesterIdSubjectSubjectIdResourcesRouteImport } from './routes/semester.$semesterId.subject.$subjectId.resources'
import { Route as SemesterSemesterIdSubjectSubjectIdBriefRouteImport } from './routes/semester.$semesterId.subject.$subjectId.brief'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SemestersRoute = SemestersRouteImport.update({
  id: '/semesters',
  path: '/semesters',
  getParentRoute: () => rootRouteImport,
} as any)
const PucExplainerRoute = PucExplainerRouteImport.update({
  id: '/puc-explainer',
  path: '/puc-explainer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SemestersIndexRoute = SemestersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SemestersRoute,
} as any)
const SemestersNewRoute = SemestersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SemestersRoute,
} as any)
const SemesterSemesterIdRoute = SemesterSemesterIdRouteImport.update({
  id: '/semester/$semesterId',
  path: '/semester/$semesterId',
  getParentRoute: () => rootRouteImport,
} as any)
const SemesterSemesterIdIndexRoute = SemesterSemesterIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SemesterSemesterIdRoute,
} as any)
const SemesterSemesterIdExportRoute =
  SemesterSemesterIdExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => SemesterSemesterIdRoute,
  } as any)
const SemesterSemesterIdEditRoute = SemesterSemesterIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SemesterSemesterIdRoute,
} as any)
const SemesterSemesterIdCalendarRoute =
  SemesterSemesterIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => SemesterSemesterIdRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SemesterSemesterIdSubjectsNewRoute =
  SemesterSemesterIdSubjectsNewRouteImport.update({
    id: '/subjects/new',
    path: '/subjects/new',
    getParentRoute: () => SemesterSemesterIdRoute,
  } as any)
const SemesterSemesterIdSubjectSubjectIdRoute =
  SemesterSemesterIdSubjectSubjectIdRouteImport.update({
    id: '/subject/$subjectId',
    path: '/subject/$subjectId',
    getParentRoute: () => SemesterSemesterIdRoute,
  } as any)
const SemesterSemesterIdSubjectSubjectIdIndexRoute =
  SemesterSemesterIdSubjectSubjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SemesterSemesterIdSubjectSubjectIdRoute,
  } as any)
const SemesterSemesterIdSubjectSubjectIdReviewRoute =
  SemesterSemesterIdSubjectSubjectIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => SemesterSemesterIdSubjectSubjectIdRoute,
  } as any)
const SemesterSemesterIdSubjectSubjectIdResourcesRoute =
  SemesterSemesterIdSubjectSubjectIdResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => SemesterSemesterIdSubjectSubjectIdRoute,
  } as any)
const SemesterSemesterIdSubjectSubjectIdBriefRoute =
  SemesterSemesterIdSubjectSubjectIdBriefRouteImport.update({
    id: '/brief',
    path: '/brief',
    getParentRoute: () => SemesterSemesterIdSubjectSubjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/dashboard': typeof DashboardRoute
  '/puc-explainer': typeof PucExplainerRoute
  '/semesters': typeof SemestersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/semester/$semesterId': typeof SemesterSemesterIdRouteWithChildren
  '/semesters/new': typeof SemestersNewRoute
  '/semesters/': typeof SemestersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/semester/$semesterId/calendar': typeof SemesterSemesterIdCalendarRoute
  '/semester/$semesterId/edit': typeof SemesterSemesterIdEditRoute
  '/semester/$semesterId/export': typeof SemesterSemesterIdExportRoute
  '/semester/$semesterId/': typeof SemesterSemesterIdIndexRoute
  '/semester/$semesterId/subject/$subjectId': typeof SemesterSemesterIdSubjectSubjectIdRouteWithChildren
  '/semester/$semesterId/subjects/new': typeof SemesterSemesterIdSubjectsNewRoute
  '/semester/$semesterId/subject/$subjectId/brief': typeof SemesterSemesterIdSubjectSubjectIdBriefRoute
  '/semester/$semesterId/subject/$subjectId/resources': typeof SemesterSemesterIdSubjectSubjectIdResourcesRoute
  '/semester/$semesterId/subject/$subjectId/review': typeof SemesterSemesterIdSubjectSubjectIdReviewRoute
  '/semester/$semesterId/subject/$subjectId/': typeof SemesterSemesterIdSubjectSubjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/dashboard': typeof DashboardRoute
  '/puc-explainer': typeof PucExplainerRoute
  '/settings': typeof SettingsRoute
  '/semesters/new': typeof SemestersNewRoute
  '/semesters': typeof SemestersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/semester/$semesterId/calendar': typeof SemesterSemesterIdCalendarRoute
  '/semester/$semesterId/edit': typeof SemesterSemesterIdEditRoute
  '/semester/$semesterId/export': typeof SemesterSemesterIdExportRoute
  '/semester/$semesterId': typeof SemesterSemesterIdIndexRoute
  '/semester/$semesterId/subjects/new': typeof SemesterSemesterIdSubjectsNewRoute
  '/semester/$semesterId/subject/$subjectId/brief': typeof SemesterSemesterIdSubjectSubjectIdBriefRoute
  '/semester/$semesterId/subject/$subjectId/resources': typeof SemesterSemesterIdSubjectSubjectIdResourcesRoute
  '/semester/$semesterId/subject/$subjectId/review': typeof SemesterSemesterIdSubjectSubjectIdReviewRoute
  '/semester/$semesterId/subject/$subjectId': typeof SemesterSemesterIdSubjectSubjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/dashboard': typeof DashboardRoute
  '/puc-explainer': typeof PucExplainerRoute
  '/semesters': typeof SemestersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/semester/$semesterId': typeof SemesterSemesterIdRouteWithChildren
  '/semesters/new': typeof SemestersNewRoute
  '/semesters/': typeof SemestersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/semester/$semesterId/calendar': typeof SemesterSemesterIdCalendarRoute
  '/semester/$semesterId/edit': typeof SemesterSemesterIdEditRoute
  '/semester/$semesterId/export': typeof SemesterSemesterIdExportRoute
  '/semester/$semesterId/': typeof SemesterSemesterIdIndexRoute
  '/semester/$semesterId/subject/$subjectId': typeof SemesterSemesterIdSubjectSubjectIdRouteWithChildren
  '/semester/$semesterId/subjects/new': typeof SemesterSemesterIdSubjectsNewRoute
  '/semester/$semesterId/subject/$subjectId/brief': typeof SemesterSemesterIdSubjectSubjectIdBriefRoute
  '/semester/$semesterId/subject/$subjectId/resources': typeof SemesterSemesterIdSubjectSubjectIdResourcesRoute
  '/semester/$semesterId/subject/$subjectId/review': typeof SemesterSemesterIdSubjectSubjectIdReviewRoute
  '/semester/$semesterId/subject/$subjectId/': typeof SemesterSemesterIdSubjectSubjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/dashboard'
    | '/puc-explainer'
    | '/semesters'
    | '/settings'
    | '/semester/$semesterId'
    | '/semesters/new'
    | '/semesters/'
    | '/api/auth/$'
    | '/semester/$semesterId/calendar'
    | '/semester/$semesterId/edit'
    | '/semester/$semesterId/export'
    | '/semester/$semesterId/'
    | '/semester/$semesterId/subject/$subjectId'
    | '/semester/$semesterId/subjects/new'
    | '/semester/$semesterId/subject/$subjectId/brief'
    | '/semester/$semesterId/subject/$subjectId/resources'
    | '/semester/$semesterId/subject/$subjectId/review'
    | '/semester/$semesterId/subject/$subjectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/dashboard'
    | '/puc-explainer'
    | '/settings'
    | '/semesters/new'
    | '/semesters'
    | '/api/auth/$'
    | '/semester/$semesterId/calendar'
    | '/semester/$semesterId/edit'
    | '/semester/$semesterId/export'
    | '/semester/$semesterId'
    | '/semester/$semesterId/subjects/new'
    | '/semester/$semesterId/subject/$subjectId/brief'
    | '/semester/$semesterId/subject/$subjectId/resources'
    | '/semester/$semesterId/subject/$subjectId/review'
    | '/semester/$semesterId/subject/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/dashboard'
    | '/puc-explainer'
    | '/semesters'
    | '/settings'
    | '/semester/$semesterId'
    | '/semesters/new'
    | '/semesters/'
    | '/api/auth/$'
    | '/semester/$semesterId/calendar'
    | '/semester/$semesterId/edit'
    | '/semester/$semesterId/export'
    | '/semester/$semesterId/'
    | '/semester/$semesterId/subject/$subjectId'
    | '/semester/$semesterId/subjects/new'
    | '/semester/$semesterId/subject/$subjectId/brief'
    | '/semester/$semesterId/subject/$subjectId/resources'
    | '/semester/$semesterId/subject/$subjectId/review'
    | '/semester/$semesterId/subject/$subjectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  DashboardRoute: typeof DashboardRoute
  PucExplainerRoute: typeof PucExplainerRoute
  SemestersRoute: typeof SemestersRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SemesterSemesterIdRoute: typeof SemesterSemesterIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semesters': {
      id: '/semesters'
      path: '/semesters'
      fullPath: '/semesters'
      preLoaderRoute: typeof SemestersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puc-explainer': {
      id: '/puc-explainer'
      path: '/puc-explainer'
      fullPath: '/puc-explainer'
      preLoaderRoute: typeof PucExplainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semesters/': {
      id: '/semesters/'
      path: '/'
      fullPath: '/semesters/'
      preLoaderRoute: typeof SemestersIndexRouteImport
      parentRoute: typeof SemestersRoute
    }
    '/semesters/new': {
      id: '/semesters/new'
      path: '/new'
      fullPath: '/semesters/new'
      preLoaderRoute: typeof SemestersNewRouteImport
      parentRoute: typeof SemestersRoute
    }
    '/semester/$semesterId': {
      id: '/semester/$semesterId'
      path: '/semester/$semesterId'
      fullPath: '/semester/$semesterId'
      preLoaderRoute: typeof SemesterSemesterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semester/$semesterId/': {
      id: '/semester/$semesterId/'
      path: '/'
      fullPath: '/semester/$semesterId/'
      preLoaderRoute: typeof SemesterSemesterIdIndexRouteImport
      parentRoute: typeof SemesterSemesterIdRoute
    }
    '/semester/$semesterId/export': {
      id: '/semester/$semesterId/export'
      path: '/export'
      fullPath: '/semester/$semesterId/export'
      preLoaderRoute: typeof SemesterSemesterIdExportRouteImport
      parentRoute: typeof SemesterSemesterIdRoute
    }
    '/semester/$semesterId/edit': {
      id: '/semester/$semesterId/edit'
      path: '/edit'
      fullPath: '/semester/$semesterId/edit'
      preLoaderRoute: typeof SemesterSemesterIdEditRouteImport
      parentRoute: typeof SemesterSemesterIdRoute
    }
    '/semester/$semesterId/calendar': {
      id: '/semester/$semesterId/calendar'
      path: '/calendar'
      fullPath: '/semester/$semesterId/calendar'
      preLoaderRoute: typeof SemesterSemesterIdCalendarRouteImport
      parentRoute: typeof SemesterSemesterIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semester/$semesterId/subjects/new': {
      id: '/semester/$semesterId/subjects/new'
      path: '/subjects/new'
      fullPath: '/semester/$semesterId/subjects/new'
      preLoaderRoute: typeof SemesterSemesterIdSubjectsNewRouteImport
      parentRoute: typeof SemesterSemesterIdRoute
    }
    '/semester/$semesterId/subject/$subjectId': {
      id: '/semester/$semesterId/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/semester/$semesterId/subject/$subjectId'
      preLoaderRoute: typeof SemesterSemesterIdSubjectSubjectIdRouteImport
      parentRoute: typeof SemesterSemesterIdRoute
    }
    '/semester/$semesterId/subject/$subjectId/': {
      id: '/semester/$semesterId/subject/$subjectId/'
      path: '/'
      fullPath: '/semester/$semesterId/subject/$subjectId/'
      preLoaderRoute: typeof SemesterSemesterIdSubjectSubjectIdIndexRouteImport
      parentRoute: typeof SemesterSemesterIdSubjectSubjectIdRoute
    }
    '/semester/$semesterId/subject/$subjectId/review': {
      id: '/semester/$semesterId/subject/$subjectId/review'
      path: '/review'
      fullPath: '/semester/$semesterId/subject/$subjectId/review'
      preLoaderRoute: typeof SemesterSemesterIdSubjectSubjectIdReviewRouteImport
      parentRoute: typeof SemesterSemesterIdSubjectSubjectIdRoute
    }
    '/semester/$semesterId/subject/$subjectId/resources': {
      id: '/semester/$semesterId/subject/$subjectId/resources'
      path: '/resources'
      fullPath: '/semester/$semesterId/subject/$subjectId/resources'
      preLoaderRoute: typeof SemesterSemesterIdSubjectSubjectIdResourcesRouteImport
      parentRoute: typeof SemesterSemesterIdSubjectSubjectIdRoute
    }
    '/semester/$semesterId/subject/$subjectId/brief': {
      id: '/semester/$semesterId/subject/$subjectId/brief'
      path: '/brief'
      fullPath: '/semester/$semesterId/subject/$subjectId/brief'
      preLoaderRoute: typeof SemesterSemesterIdSubjectSubjectIdBriefRouteImport
      parentRoute: typeof SemesterSemesterIdSubjectSubjectIdRoute
    }
  }
}

interface SemestersRouteChildren {
  SemestersNewRoute: typeof SemestersNewRoute
  SemestersIndexRoute: typeof SemestersIndexRoute
}

const SemestersRouteChildren: SemestersRouteChildren = {
  SemestersNewRoute: SemestersNewRoute,
  SemestersIndexRoute: SemestersIndexRoute,
}

const SemestersRouteWithChildren = SemestersRoute._addFileChildren(
  SemestersRouteChildren,
)

interface SemesterSemesterIdSubjectSubjectIdRouteChildren {
  SemesterSemesterIdSubjectSubjectIdBriefRoute: typeof SemesterSemesterIdSubjectSubjectIdBriefRoute
  SemesterSemesterIdSubjectSubjectIdResourcesRoute: typeof SemesterSemesterIdSubjectSubjectIdResourcesRoute
  SemesterSemesterIdSubjectSubjectIdReviewRoute: typeof SemesterSemesterIdSubjectSubjectIdReviewRoute
  SemesterSemesterIdSubjectSubjectIdIndexRoute: typeof SemesterSemesterIdSubjectSubjectIdIndexRoute
}

const SemesterSemesterIdSubjectSubjectIdRouteChildren: SemesterSemesterIdSubjectSubjectIdRouteChildren =
  {
    SemesterSemesterIdSubjectSubjectIdBriefRoute:
      SemesterSemesterIdSubjectSubjectIdBriefRoute,
    SemesterSemesterIdSubjectSubjectIdResourcesRoute:
      SemesterSemesterIdSubjectSubjectIdResourcesRoute,
    SemesterSemesterIdSubjectSubjectIdReviewRoute:
      SemesterSemesterIdSubjectSubjectIdReviewRoute,
    SemesterSemesterIdSubjectSubjectIdIndexRoute:
      SemesterSemesterIdSubjectSubjectIdIndexRoute,
  }

const SemesterSemesterIdSubjectSubjectIdRouteWithChildren =
  SemesterSemesterIdSubjectSubjectIdRoute._addFileChildren(
    SemesterSemesterIdSubjectSubjectIdRouteChildren,
  )

interface SemesterSemesterIdRouteChildren {
  SemesterSemesterIdCalendarRoute: typeof SemesterSemesterIdCalendarRoute
  SemesterSemesterIdEditRoute: typeof SemesterSemesterIdEditRoute
  SemesterSemesterIdExportRoute: typeof SemesterSemesterIdExportRoute
  SemesterSemesterIdIndexRoute: typeof SemesterSemesterIdIndexRoute
  SemesterSemesterIdSubjectSubjectIdRoute: typeof SemesterSemesterIdSubjectSubjectIdRouteWithChildren
  SemesterSemesterIdSubjectsNewRoute: typeof SemesterSemesterIdSubjectsNewRoute
}

const SemesterSemesterIdRouteChildren: SemesterSemesterIdRouteChildren = {
  SemesterSemesterIdCalendarRoute: SemesterSemesterIdCalendarRoute,
  SemesterSemesterIdEditRoute: SemesterSemesterIdEditRoute,
  SemesterSemesterIdExportRoute: SemesterSemesterIdExportRoute,
  SemesterSemesterIdIndexRoute: SemesterSemesterIdIndexRoute,
  SemesterSemesterIdSubjectSubjectIdRoute:
    SemesterSemesterIdSubjectSubjectIdRouteWithChildren,
  SemesterSemesterIdSubjectsNewRoute: SemesterSemesterIdSubjectsNewRoute,
}

const SemesterSemesterIdRouteWithChildren =
  SemesterSemesterIdRoute._addFileChildren(SemesterSemesterIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  DashboardRoute: DashboardRoute,
  PucExplainerRoute: PucExplainerRoute,
  SemestersRoute: SemestersRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SemesterSemesterIdRoute: SemesterSemesterIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
