/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SemestersRouteImport } from './routes/semesters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SemestersNewRouteImport } from './routes/semesters.new'
import { Route as SemesterSemesterIdRouteImport } from './routes/semester.$semesterId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as SemesterSemesterIdIndexRouteImport } from './routes/semester.$semesterId.index'
import { Route as SemesterSemesterIdEditRouteImport } from './routes/semester.$semesterId.edit'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as SemesterSemesterIdSubjectsNewRouteImport } from './routes/semester.$semesterId.subjects.new'
import { Route as SemesterSemesterIdSubjectSubjectIdRouteImport } from './routes/semester.$semesterId.subject.$subjectId'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as SemesterSemesterIdSubjectSubjectIdIndexRouteImport } from './routes/semester.$semesterId.subject.$subjectId.index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SemestersRoute = SemestersRouteImport.update({
  id: '/semesters',
  path: '/semesters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SemestersNewRoute = SemestersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SemestersRoute,
} as any)
const SemesterSemesterIdRoute = SemesterSemesterIdRouteImport.update({
  id: '/semester/$semesterId',
  path: '/semester/$semesterId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SemesterSemesterIdIndexRoute = SemesterSemesterIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SemesterSemesterIdRoute,
} as any)
const SemesterSemesterIdEditRoute = SemesterSemesterIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SemesterSemesterIdRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const SemesterSemesterIdSubjectsNewRoute =
  SemesterSemesterIdSubjectsNewRouteImport.update({
    id: '/subjects/new',
    path: '/subjects/new',
    getParentRoute: () => SemesterSemesterIdRoute,
  } as any)
const SemesterSemesterIdSubjectSubjectIdRoute =
  SemesterSemesterIdSubjectSubjectIdRouteImport.update({
    id: '/subject/$subjectId',
    path: '/subject/$subjectId',
    getParentRoute: () => SemesterSemesterIdRoute,
  } as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const SemesterSemesterIdSubjectSubjectIdIndexRoute =
  SemesterSemesterIdSubjectSubjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SemesterSemesterIdSubjectSubjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/semesters': typeof SemestersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/semester/$semesterId': typeof SemesterSemesterIdRouteWithChildren
  '/semesters/new': typeof SemestersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/semester/$semesterId/edit': typeof SemesterSemesterIdEditRoute
  '/semester/$semesterId/': typeof SemesterSemesterIdIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/semester/$semesterId/subject/$subjectId': typeof SemesterSemesterIdSubjectSubjectIdRouteWithChildren
  '/semester/$semesterId/subjects/new': typeof SemesterSemesterIdSubjectsNewRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/semester/$semesterId/subject/$subjectId/': typeof SemesterSemesterIdSubjectSubjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/semesters': typeof SemestersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/semesters/new': typeof SemestersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/semester/$semesterId/edit': typeof SemesterSemesterIdEditRoute
  '/semester/$semesterId': typeof SemesterSemesterIdIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/semester/$semesterId/subjects/new': typeof SemesterSemesterIdSubjectsNewRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/semester/$semesterId/subject/$subjectId': typeof SemesterSemesterIdSubjectSubjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/semesters': typeof SemestersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/semester/$semesterId': typeof SemesterSemesterIdRouteWithChildren
  '/semesters/new': typeof SemestersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/semester/$semesterId/edit': typeof SemesterSemesterIdEditRoute
  '/semester/$semesterId/': typeof SemesterSemesterIdIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/semester/$semesterId/subject/$subjectId': typeof SemesterSemesterIdSubjectSubjectIdRouteWithChildren
  '/semester/$semesterId/subjects/new': typeof SemesterSemesterIdSubjectsNewRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/semester/$semesterId/subject/$subjectId/': typeof SemesterSemesterIdSubjectSubjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/semesters'
    | '/settings'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/semester/$semesterId'
    | '/semesters/new'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/semester/$semesterId/edit'
    | '/semester/$semesterId/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/semester/$semesterId/subject/$subjectId'
    | '/semester/$semesterId/subjects/new'
    | '/demo/start/ssr/'
    | '/semester/$semesterId/subject/$subjectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/semesters'
    | '/settings'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/semesters/new'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/semester/$semesterId/edit'
    | '/semester/$semesterId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/semester/$semesterId/subjects/new'
    | '/demo/start/ssr'
    | '/semester/$semesterId/subject/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/semesters'
    | '/settings'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/semester/$semesterId'
    | '/semesters/new'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/semester/$semesterId/edit'
    | '/semester/$semesterId/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/semester/$semesterId/subject/$subjectId'
    | '/semester/$semesterId/subjects/new'
    | '/demo/start/ssr/'
    | '/semester/$semesterId/subject/$subjectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SemestersRoute: typeof SemestersRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  SemesterSemesterIdRoute: typeof SemesterSemesterIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semesters': {
      id: '/semesters'
      path: '/semesters'
      fullPath: '/semesters'
      preLoaderRoute: typeof SemestersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semesters/new': {
      id: '/semesters/new'
      path: '/new'
      fullPath: '/semesters/new'
      preLoaderRoute: typeof SemestersNewRouteImport
      parentRoute: typeof SemestersRoute
    }
    '/semester/$semesterId': {
      id: '/semester/$semesterId'
      path: '/semester/$semesterId'
      fullPath: '/semester/$semesterId'
      preLoaderRoute: typeof SemesterSemesterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semester/$semesterId/': {
      id: '/semester/$semesterId/'
      path: '/'
      fullPath: '/semester/$semesterId/'
      preLoaderRoute: typeof SemesterSemesterIdIndexRouteImport
      parentRoute: typeof SemesterSemesterIdRoute
    }
    '/semester/$semesterId/edit': {
      id: '/semester/$semesterId/edit'
      path: '/edit'
      fullPath: '/semester/$semesterId/edit'
      preLoaderRoute: typeof SemesterSemesterIdEditRouteImport
      parentRoute: typeof SemesterSemesterIdRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semester/$semesterId/subjects/new': {
      id: '/semester/$semesterId/subjects/new'
      path: '/subjects/new'
      fullPath: '/semester/$semesterId/subjects/new'
      preLoaderRoute: typeof SemesterSemesterIdSubjectsNewRouteImport
      parentRoute: typeof SemesterSemesterIdRoute
    }
    '/semester/$semesterId/subject/$subjectId': {
      id: '/semester/$semesterId/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/semester/$semesterId/subject/$subjectId'
      preLoaderRoute: typeof SemesterSemesterIdSubjectSubjectIdRouteImport
      parentRoute: typeof SemesterSemesterIdRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semester/$semesterId/subject/$subjectId/': {
      id: '/semester/$semesterId/subject/$subjectId/'
      path: '/'
      fullPath: '/semester/$semesterId/subject/$subjectId/'
      preLoaderRoute: typeof SemesterSemesterIdSubjectSubjectIdIndexRouteImport
      parentRoute: typeof SemesterSemesterIdSubjectSubjectIdRoute
    }
  }
}

interface SemestersRouteChildren {
  SemestersNewRoute: typeof SemestersNewRoute
}

const SemestersRouteChildren: SemestersRouteChildren = {
  SemestersNewRoute: SemestersNewRoute,
}

const SemestersRouteWithChildren = SemestersRoute._addFileChildren(
  SemestersRouteChildren,
)

interface SemesterSemesterIdSubjectSubjectIdRouteChildren {
  SemesterSemesterIdSubjectSubjectIdIndexRoute: typeof SemesterSemesterIdSubjectSubjectIdIndexRoute
}

const SemesterSemesterIdSubjectSubjectIdRouteChildren: SemesterSemesterIdSubjectSubjectIdRouteChildren =
  {
    SemesterSemesterIdSubjectSubjectIdIndexRoute:
      SemesterSemesterIdSubjectSubjectIdIndexRoute,
  }

const SemesterSemesterIdSubjectSubjectIdRouteWithChildren =
  SemesterSemesterIdSubjectSubjectIdRoute._addFileChildren(
    SemesterSemesterIdSubjectSubjectIdRouteChildren,
  )

interface SemesterSemesterIdRouteChildren {
  SemesterSemesterIdEditRoute: typeof SemesterSemesterIdEditRoute
  SemesterSemesterIdIndexRoute: typeof SemesterSemesterIdIndexRoute
  SemesterSemesterIdSubjectSubjectIdRoute: typeof SemesterSemesterIdSubjectSubjectIdRouteWithChildren
  SemesterSemesterIdSubjectsNewRoute: typeof SemesterSemesterIdSubjectsNewRoute
}

const SemesterSemesterIdRouteChildren: SemesterSemesterIdRouteChildren = {
  SemesterSemesterIdEditRoute: SemesterSemesterIdEditRoute,
  SemesterSemesterIdIndexRoute: SemesterSemesterIdIndexRoute,
  SemesterSemesterIdSubjectSubjectIdRoute:
    SemesterSemesterIdSubjectSubjectIdRouteWithChildren,
  SemesterSemesterIdSubjectsNewRoute: SemesterSemesterIdSubjectsNewRoute,
}

const SemesterSemesterIdRouteWithChildren =
  SemesterSemesterIdRoute._addFileChildren(SemesterSemesterIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SemestersRoute: SemestersRouteWithChildren,
  SettingsRoute: SettingsRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  SemesterSemesterIdRoute: SemesterSemesterIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
